"""empty message

Revision ID: efa0bcfaaace
Revises: 
Create Date: 2020-07-06 23:11:58.302118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa0bcfaaace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('Movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('Roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('role_desc', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.actor_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.movie_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Roles')
    op.drop_table('Movies')
    op.drop_table('Actors')
    # ### end Alembic commands ###
